### ISSUE TITLE
/bin/sh: yarn: command not found

### ISSUE THREAD

**Issue by aiboy** [sdras/project-explorer#13]
Tnx a lot for this awesome project. I don't have yarn installed on my PC and I get this error ```/bin/sh: yarn: command not found``` Can you handle this situation gracefully? (by using npm if yarn is not presented)

**Comment by sdras** [comment]
Hi there! I do tell people that Yarn is a requirement for the project, it's in the documentation and the in the readme. You could run `npm i -g yarn` if you'd like to add it. I tried it both ways and the yarn install is much faster and cleaner so I would like to head in that direction.

I'm going to close this out for now but I am open to changing my mind on it if it's bothering a lot of people. :)

**Comment by aiboy** [comment]
@sdras I had a lot of problems with yarn, so now I try to avoid using it. Anyway, thanks again for this awesome project! For now I will install dependencies manually, by typing ```npm install``` in project folder :)
