### ISSUE TITLE
1. Cannot read property 'push' of undefined 2. using project-explorer locally

### ISSUE THREAD

**Issue by hex13** [sdras/project-explorer#17]
I've installed it locally (npm i --save-dev project-explorer)

Then I ran:
> node_modules/.bin/pexx abc 

But error appeared (UnhandledPromiseRejectionWarning)
```
path: .
‣ Name of Project: abc
‣ Path: .
(node:5535) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'push' of undefined
    at /Users/lukasz/sandbox/resmix/node_modules/project-explorer/index.js:70:21
    at Generator.next (<anonymous>)
    at onFulfilled (/Users/lukasz/sandbox/resmix/node_modules/co/index.js:65:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5535) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5535) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````
Then I manually edited `index.js` in `node_modules/project-eplorer/` and changed:

```javascript
const gitignoredArr = gitignoreRegex(pathDir)
```
into
```javascript
 const gitignoredArr = gitignoreRegex(pathDir) || [];
```
and then it worked... almost. It generated `base-directory-tree` but it wasn't able to run it
```
Your files were saved, now let's build it out! ✨
Hang tight, this might take a minute.
yarn install v0.15.1
info No lockfile found.
[1/4] Resolving packages...
warning @vue/cli-service > webpack-bundle-analyzer > bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning Unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning Incorrect peer dependency "@babel/core@^7.0.0".
warning Unmet peer dependency "webpack@>=2".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 42.98s.
🎸 Done! Built with success! Now let's get you a server.
yarn serve v0.15.1
$ "vue-cli-service serve --open" 
sh: vue-cli-service serve --open: command not found
error Command failed with exit code 127.
info Visit http://yarnpkg.com/en/docs/cli/serve for documentation about this command.
exec: sh: vue-cli-service serve --open: command not found
error Command failed with exit code 127.
```

Then I've run `cd base-directory-tree` and `npm start` but it also didn't run

```
> drawtree@0.1.0 start /Users/lukasz/sandbox/resmix/base-directory-tree
> npm run dev

npm ERR! missing script: dev
```
UPDATE:  I ran `node_modules/.bin/vue-cli-service serve --open` from `base-directory-tree` and a file tree was appeared  on `http://localhost:8080/` but anyway...

It seems like I stumbled upon two different issues:

1. `push` problem (which I resolved by manually adding `|| []` )
2.  this projects seems to assume global installing. Is this special reason for that? I prefer to install things locally and it would be nice if it worked out of the box when installing locally.

**Comment by sdras** [comment]
This isn't how you should use it locally- can you please run `node index.js nameofyourproject` as outlined in CONTRIBUTING.md (after it's been installed). Let me know if that doesn't work. Thanks!

**Comment by hex13** [comment]
So it looks that error `Cannot read property 'push' of undefined` throws at 
https://github.com/sdras/project-explorer/blob/master/index.js#L68
but the real culprit is  gitignoreRegex function which returns undefined, in case of missing .gitignore:
```javascript
} catch (err) { return }
```
https://github.com/sdras/project-explorer/blob/master/index.js#L47

In other words error occurs when there is no `.gitignore` in analyzed project.

Because `gitignoreRegex` seems to return array, I suppose the solution would be replace 

```javascript
} catch (err) { return }
```

with 
```javascript
} catch (err) { return [] }
```
(Would you accept PR?)

(related issue: #8)

**Comment by sdras** [comment]
Good call, yes I would accept a PR for this :)

**Comment by hex13** [comment]
Ok, I made a PR 
https://github.com/sdras/project-explorer/pull/19 :)

**Comment by sdras** [comment]
Merged! 🎉Thank you.
