### ISSUE TITLE
How to add comments to subdirectories

### ISSUE THREAD

**Issue by ArsSirek** [sdras/project-explorer#18]
For example, If have e structure like:
-common
--models

how do I add an info to a models directory?

Adding something like `"common.models": "Info text"` to comments section of `store.js`

Sorry if I missed some documentation, nice work!

**Comment by debs-obrien** [comment]
Hi you can just use "common/models": 'Info text'

**Comment by sdras** [comment]
Hi @ArsSirek! 

The comment above by @debs-obrien is correct :) For reference you can always check `tree.js` to see how the path is defined. I'll update the docs to be more explicit.
