### ISSUE TITLE
`tree` is already a Unix command, so `tree nameofmyproject` fails.

### ISSUE THREAD

**Issue by phacks** [sdras/project-explorer#2]
Hi! This CLI looks amazing for onboarding new developers on a project with a large codebase 😊

However I ran into a problem while trying it out: I already have a [`tree` command](https://www.computerhope.com/unix/tree.htm) on my `$PATH`, so running `tree nameofmyproject` tries to run the “Unix” `tree`. As this command is fairly popular, I wouldn’t be surprised if other people have the same problem.

A solution for now is to type the full path for the project-explorer’s `tree` binary, e.g. `/Users/nico/.nvm/versions/node/v8.11.3/bin/tree`.

Do you think it would be possible to change the name of the executable, e.g. to `project-explorer` or some other fancier name? I’m willing to do a PR on the matter.

Thanks!

**Comment by phacks** [comment]
Another solution would be to `alias` it locally, in which case I can update the docs so that it’s easier to install.

**Comment by sdras** [comment]
Yes! I'm going to fix this right away. Thanks! 🤘

**Comment by sdras** [comment]
ok, should be fixed! please upgrade (`npm i -g project-explorer`) and use the command `pexx` instead, as in `pexx yourprojectnamehere`. Thanks!
