### ISSUE TITLE
Remove .DS_Store

### ISSUE THREAD

**Issue by sdras** [sdras/project-explorer#3]
Remove unneeded files like .DS_Store. Possibly node_modules as well.

**Comment by farskid** [comment]
I think this is related to https://github.com/sdras/project-explorer/issues/8

Is there any case in which we need to cover .gitignore files?

**Comment by sdras** [comment]
Yeah, I think we would read what's in `.gitignore` and then exclude them. I can probably make a small PR that removes `.DS_Store` and `node_modules` very quickly. The .`gitignore idea` might take a bit longer because if it takes some time to run and has to do error handling we might also need a loader. But it would be much more elegant so I think that's what we should do eventually.

**Comment by sdras** [comment]
This is now done! See https://github.com/sdras/project-explorer/issues/8 for more info 🎉
