### ISSUE TITLE
Ignore files and folders from '.gitignore'

### ISSUE THREAD

**Issue by saneef** [sdras/project-explorer#8]
Wouldn't be nice if we ignore files which are included in the `.gitignore`?

**Comment by benmccallum** [comment]
I think this is fair, but it gets tricky when, say, you want to annotate/document the district folder or some other output folder that is gitignored.

Maybe you support gitignore and then have a similar pattern to forcing a file to be tracked for forcing a folder/file to be added to Project Explorer, so a CMD like `pexx add "my/path/xyz" -f`

**Comment by easingthemes** [comment]
PR #12 
@benmccallum You can temporarily remove that match from gitignore when building project structure.

**Comment by sdras** [comment]
I love this and merged the PR, but I do think @benmccallum has a point and I will try to make another command that allows you to add back in files. PRs also welcome. Thank you!
